### PR TITLE
fix(deps): bump minipass

### PR DESCRIPTION
**Pull request by ThaUnknown**
updates minipass, as the currently used version has a bug which prevents it from correctly finishing

### CODE REVIEW

**Comment by vweevers** [comment]
`minipass` is pinned because of https://github.com/vweevers/tap-completed/commit/3bb345a0f3b736a4134abd120feb0dc91af03366, which I think is fixed by now, but if so we need to bump `tap-parser` as well.

**Comment by ThaUnknown** [comment]
> `minipass` is pinned because of [3bb345a](https://github.com/vweevers/tap-completed/commit/3bb345a0f3b736a4134abd120feb0dc91af03366), which I think is fixed by now, but if so we need to bump `tap-parser` as well.

forcing the version to 3.3.6 didn't cause any issues so idk

**Comment by vweevers** [comment]
> didn't cause any issues

As in, `npm test` passes?

**Comment by ThaUnknown** [comment]
> > didn't cause any issues
> 
> As in, `npm test` passes?

sorry I should have been more specific, I simply configured pnpm to ignore pins, and use latest version for that major version, and everything worked fine for this, by "everything" I mean running airtap with some abstract tests

so you might be right that other dependencies need to be bumped too, as I didn't look at that

**Comment by vweevers** [comment]
I had a look at latest `tap-parser` and it doesn't use `minipass` anymore. It also doesn't extend Node.js streams, but instead implements `WritableStream` as a TS interface. That interface doesn't cover events (and their timing) so we'll have to check how compatible it is. In any case, it'll require a major bump here (and in `airtap`), for dropping support of Node.js 10.

**Comment by vweevers** [comment]
Fixed by #3. An airtap update will follow.

Thanks for the PR!

**Pull request closed without merging**
